language: node_js
dist: xenial
sudo: required

node_js:
  - 'node'
# cache: yarn
before_install:
  - sudo apt-get install -y sshpass
install:
  - echo haha
# script:
#   - yarn build
after_script:
  - sshpass -p $SSH_PASS scp package.json  $SSH_USER@$SSH_IP:/usr/share/nginx/html/lab
branches:
  only:
    - master
