language: node_js
dist: xenial
sudo: required

node_js:
  - 'node'
cache: yarn
before_install:
  - sudo apt-get install -y sshpass
install:
  - yarn install
script:
  - yarn build
after_script:
  - echo "$SSH_KNOWN_HOST" > ~/.ssh/known_hosts
  - sshpass -p $SSH_PASS scp -r dist/*  $SSH_USER@$SSH_IP:/usr/share/nginx/lab
branches:
  only:
    - master
